### ISSUE TITLE
Hidden Game Results

### ISSUE THREAD

**Issue by doilio** [callebdev/NumberGuess#4]
When I play the game the Results are hidden because of the keyboard.

![device-2020-03-20-224447](https://user-images.githubusercontent.com/38020305/77205137-dec55a80-6afc-11ea-8f8b-8c2fc7a86179.png)

I Would like to suggest that you hid the keyboard after pressing **DO GUESS**

![device-2020-03-20-224506](https://user-images.githubusercontent.com/38020305/77205149-e258e180-6afc-11ea-8d9f-5a05241af253.png)

**Comment by callebdev** [comment]
Thanks for reporting me! I'll consider hiding the keyboard after the DO GUESS button be clicked. :)
